#!/bin/bash

MOUNTPOINT=/userdata
RESULTDIR=${HOME}/runos-docker/runos/functest/results
PWD=`pwd`
RUNOS_PORT=8000

docker run --rm --privileged -ti \
       -e DEV_UID=$UID \
       -e DEV_USER=$USER \
       -v $PWD:$MOUNTPOINT \
       -v $RESULTDIR:$MOUNTPOINT/results \
       -v /usr/src:/usr/src \
       -v /lib/modules:/lib/modules \
       -v /linux-kernel:/linux-kernel \
       -p 127.0.0.1:$RUNOS_PORT:$RUNOS_PORT \
       -h frenetic \
       frenetic
